services:
  - type: web
    name: assetflow
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma db push --schema server/prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
